# Generated by Django 5.0.4 on 2024-04-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('url_socket', models.TextField(default='NULL', verbose_name='url')),
                ('users_count', models.IntegerField(default=0, verbose_name='users_count')),
            ],
            options={
                'verbose_name': 'Lobby',
                'verbose_name_plural': 'Lobbies',
            },
        ),
    ]
