# Generated by Django 3.2.25 on 2024-05-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='users_count',
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(default='NULL', verbose_name='name')),
                ('is_master', models.BooleanField(default=False, verbose_name='master')),
                ('lobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(default='NULL', verbose_name='text')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lobby.users')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
