# Generated by Django 3.2.25 on 2024-05-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_auto_20240503_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='url_socket',
        ),
    ]
