# Generated by Django 3.2.25 on 2024-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_remove_lobby_url_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='url_socket',
            field=models.TextField(default='NULL', verbose_name='url'),
        ),
    ]
