# Generated by Django 3.2.25 on 2024-05-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_users_lobby_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
