# Generated by Django 3.2.25 on 2024-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
