# Generated by Django 3.2.25 on 2024-03-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'verbose_name': 'Lobby', 'verbose_name_plural': 'Lobby'},
        ),
    ]
