# Generated by Django 3.2.25 on 2024-04-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lobby_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
