# Generated by Django 4.2.11 on 2024-04-11 12:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('websocketapp', '0005_alter_lobby_options_remove_lobby_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='users_id',
            field=models.CharField(default=[0], max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='USERS ID'),
        ),
    ]
