# Generated by Django 4.2.11 on 2024-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketapp', '0006_alter_lobby_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='users_quantity',
        ),
        migrations.AddField(
            model_name='lobby',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='USERS COUNT'),
        ),
    ]
